qb_stimulus:
  channel: DAC2
  channel_config:
    vop: 30000 # Gain of the DAC, ~ 2000-40000
    mix_reconstruction: true # flase # for scope check # Set to falso for zero order hold (ZOH) reconstruction
    nco_frequency: 8.047785109e+9 # 50e6 # for scope check
  pulses:
    R_x_180:
      data: hann
      scale: 0.27814
      ramp: 120e-9 # Both up and down ramps
      flat: 100e-9
      use_stretch: true
    R_x_180_selective:
      data: hann
      scale: 0.05228
      ramp: 400e-9
      flat: 5e-6
      use_stretch: true
    R_x_90:
      data: hann
      scale: 0.32665
      ramp: 120e-9
      flat: 100e-9
      use_stretch: true
    R_x_180_selective_ef:
      data: hann
      scale: 0.04036
      ramp: 400e-9
      flat: 5e-6
      detune: -1.512e+8
      use_stretch: false
    R_x_180_ef:
      data: hann
      scale: 0.38864
      ramp: 400e-9
      detune: -1.512e+8
      use_stretch: false

ro_stimulus:
  channel: DAC0
  channel_config:
    vop: 35000
    mix_reconstruction: true
    nco_frequency: 9.309035232e+9 # 8.9985e9 # 9.00057e9 # 20e6 # 8.9995e9 # 9.0004e9
  pulses:
    readout:
      data: hann
      scale: (0.35, 0deg)
      ramp: 120e-9
      flat: 2e-6
      use_stretch: true

ro_capture:
  channel: ADC0
  channel_config:
    nco_frequency: 9.309035232e+9 # 8.9985e9 # 9.00057e9 # 9.0004e9
  memories:
    readout_trace:
      length: 3e-6
      decimation: 4
      region: plddr
    readout_accumulated:
      length: 3e-6
      decimation: 0
      region: plddr
  windows:
    boxcar:
      data: 0.1
      offset: [0, 0]
    matched:
      data: 0.1
      offset: [61, 3638]
    matched_biased_g:
      data: 0.1
      offset: [-939, 3638]
  classifiers:
    default:
      type: RealQuadratureClassifier
    rotated_iq:
      type: MaximalVarianceAxisClassifier


qb_alice_bs_stimulus:
  channel: DAC6 # DAC7 for scope check, DAC6 for normal operation
  channel_config:
    vop: 30000
    mix_reconstruction: false
    nco_frequency: 1.84396931e+9  # 20e6 # for scope check
  pulses:
    swap_stretchable:
      data: hann
      scale: 0.036
      ramp: 120e-9
      flat: 100e-9
      use_stretch: true
    swap:
      data: hann
      scale: 0.1
      ramp: 120e-9
      flat: 3.5e-8
      use_stretch: false
    bs_50_50:
      data: hann
      scale: 0.036
      ramp: 120e-9
      flat: 100e-9
      use_stretch: true
    dChi_pump:
      data: hann
      scale: 0.1
      ramp: 120e-9
      flat: 100e-9
      use_stretch: true
    dChi_parity_map:
      data: hann
      scale: 0.1
      ramp: 120e-9
      flat: 100e-9
      use_stretch: true
