from typing import Callable, Tuple
import os
import pickle
import logging
import numpy as np
from matplotlib.figure import Figure
from matplotlib.widgets import Button
import matplotlib.pyplot as plt

from acadia import Runtime
from acadia_qmsmt.helpers import get_registered_plot_methods, get_data_process_method

logger = logging.getLogger(__name__)


def prepare_plot_axes(axs, axs_shape=(1, 1), **subplot_kwargs):
    """
    Prepare the figure and axes for plotting. This is just a simple shortcut function that does
    the things we would usually do in a plot method that takes optional plot axs.

    If `axs` is None, create a new subplot grid using `axs_shape`.
    If `axs` is provided, attempt to extract the corresponding figure.

    :param axs:
    :param axs_shape: unfortunately, we still have to provide this even though we might
        have already provided it in the decorator
    :return:
    """
    if axs is None:
        fig, axs = plt.subplots(*axs_shape, **subplot_kwargs)
        return fig, axs

    try:
        fig = np.asarray(axs).flat[0].figure
    except Exception:
        fig = axs.figure
    return fig, axs


def save_registered_plots(runtime: Runtime, save_pickle=True, do_process=True, transparent=True) -> None:
    """
    Do a final plot on all registered plot methods and save the figures.

    :param runtime: Runtime object that has the registered plot methods.
    :param save_pickle: If True, save a copy of the pickled plot
    :param do_process: If True, re-run the data processing method tagged by `DATA_PROCESS_TAG=True`
        before plotting the data
    :param transparent: If True, save png with transparent background
    :return:
    """
    import matplotlib
    # Save the current backend
    current_backend = matplotlib.get_backend()

    try:
        # Use headless backend for safe figure saving
        matplotlib.use("agg", force=True)

        if do_process:
            data_process_method_name = get_data_process_method(runtime)
            getattr(runtime, data_process_method_name)()

        plots = get_registered_plot_methods(runtime)
        for plot_name, method_name in plots.items():
            figure = None
            try:
                figure, _ = getattr(runtime, method_name)()
                image_filename = os.path.join(runtime.local_directory, f"{plot_name}.png")
                figure.savefig(image_filename, dpi=500, transparent=transparent)

                if save_pickle:
                    with open(os.path.join(runtime.local_directory, f"{plot_name}.pkl"), "wb") as f:
                        pickle.dump(figure, f)

            except Exception as e:
                logger.warning(f"Can't save figure {plot_name} generated by {method_name}: {e}")
            finally:
                if figure:
                    plt.close(figure)

    finally:
        # Restore previous backend
        matplotlib.use(current_backend, force=True)


# ----------------------- ipython console helpers ------------------------------------------------------------

def add_button(fig: Figure, event: Callable, label: str = "Update", size: Tuple[float, float] = (None, None)):
    """
    Add a button to the bottom of a figure. Run the `event` when the button is clicked.
    The caller must maintain a reference to the returned widget object for the button to be active.

    This function is useful when generating interactive plots in ipython consoles.
    For acadia_gui, directly decorating the update functions with annotation `button_name=...` is easier.

    :param fig: Figure to which the button is added
    :param event: The function to call when the button is clicked
    :param label: Label text displayed on the button
    :param size: Width and height of the button as fractions of the figure size
    :return: The axes of the newly created button and the button widget.
    """

    axes = fig.get_axes()

    # Initialize button metadata if not already present
    button_w, button_h = size
    if not hasattr(fig, "_button_positions"):
        fig.tight_layout()
        if button_h is None:
            button_h = 0.1 * 1 / len(axes)
        fig._button_positions = {"row_widths": [[]], "row_heights": [button_h], "n_plots": len(axes)}

    if button_w is None:
        button_w = len(label) * 0.02

    # use the height of the last button if button height is not provided
    button_h = fig._button_positions["row_heights"][-1] if button_h is None else button_h

    # find space for the new button and rearrange the old ones
    max_w = 0.97
    current_row_w = np.sum(fig._button_positions["row_widths"][-1])

    if current_row_w + button_w < max_w:
        fig._button_positions["row_widths"][-1].append(button_w)
        fig._button_positions["row_heights"][-1] = button_h
    else:
        fig._button_positions["row_widths"].append([button_w])
        fig._button_positions["row_heights"].append(button_h)

    # update the position of the previous buttons in the row
    last_row_widths = fig._button_positions["row_widths"][-1]
    x0 = (max_w - np.sum(last_row_widths)) / 2
    for i, w in enumerate(last_row_widths[:-1]):
        button_ax = axes[-len(last_row_widths) + i + 1]
        button_pos = (x0, button_ax.get_position().ymin, w, button_h)
        button_ax.set_position(button_pos)
        x0 += w

    # Adjust the layout to make space for the buttons when a new row is added
    if len(last_row_widths) == 1:
        ax_bottom = axes[fig._button_positions["n_plots"] - 1].get_position().ymin
        fig.subplots_adjust(bottom=ax_bottom + button_h)

    # position for the new button
    y0 = 0.01 + np.sum(fig._button_positions["row_heights"]) - button_h
    button_pos = (x0, y0, button_w, button_h)

    # add the new button
    button_ax = fig.add_axes(button_pos)
    button = Button(button_ax, label)
    button.on_clicked(event)

    return button_ax, button


if __name__ == "__main__":
    import matplotlib

    matplotlib.use('qt5agg')
    plt.ion()


    def on_button_click():
        print(f"Button clicked!")


    # Create a figure with a grid of subplots
    fig, axs = plt.subplots(3, 1, figsize=(5, 8))  # 2x2 grid of subplots
    for ax in axs.flat:
        ax.plot([0, 1], [0, 1])  # Example plot
        ax.set_xlabel("X-axis Label")
        ax.set_ylabel("Y-axis Label")
    fig.tight_layout()

    # Add a button at the bottom of the figure
    button_ax, button = add_button(fig, label="Click Me", event=on_button_click)
    button_ax1, button1 = add_button(fig, label="Click Me 2", event=on_button_click)
    # button_ax2, button2 = add_button(fig, label="Click Me", event=func)

    plt.show()
