q_stimulus:
  channel: DAC0
  channel_config:
    vop: 20000
    mix_reconstruction: true
    nco_frequency: 8229954037.0
  waveforms:
    q_rotation:
      length: 40.0e-9
      fixed_length: 200.0e-9
  signals:
    pi_pulse:
      data: [scipy, hann]
      scale: 0.27
    pi_2_pulse:
      data: [scipy, hann]
      scale: 0.141

ro_stimulus:
  channel: DAC2
  channel_config:
    vop: 25000
    mix_reconstruction: true
    nco_frequency: 9.030e9
  waveforms:
    ro_drive:
      length: 40.e-9
      fixed_length: 1.6e-6
  signals:
    readout:
      data: [scipy, hann]
      scale: (0.5, 180deg)

ro_capture:
  channel: ADC0
  channel_config:
    nco_frequency: -9.030e9
  waveforms:
    readout_trace:
      length: 2.4e-6
      decimation: 4
      region: plddr
    readout_accumulated:
      length: 2.4e-6
      decimation: 0
      region: plddr
  capture_delay: 300e-9
  kernels: 
    boxcar: 
      data: -0.1
      offset: 500 + 3j
  state_quadrants: [4, 3]
